### ISSUE TITLE
Godot 4 build fails with [gen\include\godot_cpp\core\ext_wrappers.gen.inc] KeyError : 'is_bitfield'

### ISSUE THREAD

**Issue by Darker** [godotengine/godot-cpp#1099]
The first time I tried to build Godot 4 cpp bindings was couple months ago, and while painful it was possible.

I unfortunatelly do not remember what workarounds I used then, but now I get this error on my system:

Command:
```
scons platform=windows -j10 custom_api_file="D:\\MYFOLDER\\Godot\\extension_api.json"
```

Result, before that it logs a JSON array with a list of source files.
```
Built-in type config: float_64
scons: *** [gen\include\godot_cpp\core\ext_wrappers.gen.inc] KeyError : 'is_bitfield'
Traceback (most recent call last):
  File "C:\PYTHON_HOME\Python310\site-packages\SCons\Action.py", line 1318, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "D:\MYFOLDER\programming\godot_shared-library\cpp\lib\godot-cpp\binding_generator.py", line 149, in scons_generate_bindings
    generate_bindings(
  File "D:\MYFOLDER\programming\godot_shared-library\cpp\lib\godot-cpp\binding_generator.py", line 174, in generate_bindings
    generate_global_constant_binds(api, target_dir)
  File "D:\MYFOLDER\programming\godot_shared-library\cpp\lib\godot-cpp\binding_generator.py", line 1624, in generate_global_constant_binds
    if enum_def["is_bitfield"]:
KeyError: 'is_bitfield'
scons: building terminated because of errors.
```

I did not change anything else.

**Comment by Darker** [comment]
This is caused by an outdated version of the godot editor, which produced outdated ;extension_api.json;

**Comment by paddy-exe** [comment]
Could you please supply the commit of godot-cpp and your Godot build that you used for compilation?

**Comment by paddy-exe** [comment]
Please try again with the 4.0.2 version of the editor build

**Comment by Darker** [comment]
Yes, it works in 4.0.2. I thought I closed the issue with the first comment. I am closing it now, I guess I forgot.
